 # This should be pinned in a prod deployment
FROM ghcr.io/zitadel/zitadel:latest

COPY ./docker/certificate.crt /usr/local/share/ca-certificates/certificate.crt
COPY ./docker/private.key /usr/local/share/ca-certificates/private.key
